# Generated by Django 3.1.2 on 2020-11-17 06:34

from django.db import migrations, models
import recognition.models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognition',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='recognition',
            name='image',
            field=models.ImageField(default='media/default_image.jpg', null=True, upload_to=recognition.models.Recognition.date_upload_to),
        ),
    ]
