# Generated by Django 3.1.2 on 2020-11-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_auto_20201117_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognition',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
