# Generated by Django 3.1.2 on 2020-11-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0004_auto_20201118_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognition',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
