# Generated by Django 3.1.2 on 2020-11-17 04:01

import api_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Please Register Location', max_length=20, null=True)),
                ('sublocation', models.CharField(default='Please Register Sub Location', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(null=True)),
                ('image', models.ImageField(default='media/default_image.jpg', upload_to=api_app.models.File.date_upload_to)),
                ('location', models.CharField(default='Please Register Location', max_length=20, null=True)),
                ('sublocation', models.CharField(default='Please Register Sub Location', max_length=20, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
