# Generated by Django 3.1.2 on 2020-11-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(default='Please Register Location', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='sublocation',
            field=models.CharField(default='Please Register Sub Location', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='location',
            field=models.CharField(default='Please Register Location', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='sublocation',
            field=models.CharField(default='Please Register Sub Location', max_length=50, null=True),
        ),
    ]
