# Generated by Django 3.1.2 on 2020-11-17 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20201117_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='owner',
        ),
    ]
